---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: staging-listener
  namespace: tekton-staging
spec:
  serviceAccountName: staging-triggers-admin
  triggers:
    - bindings:
      - ref: staging-pipelinebinding
      template:
        ref: staging-triggertemplate
      interceptors:
        - cel:
            # TODO: This is a reminder that this should match the HookSecret
            # on internal/cli/clients/client.go
            # If this filter is not set, anyone can trigger a staging job simply
            # by posting to the webhook.
            # More here: https://github.com/epinio/epinio/issues/130#issuecomment-813314112
            filter: "body.secret == '74tZTBHkhjMT5Klj6Ik6PqmM'"
