apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: staging-triggertemplate
  namespace: tekton-staging
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
    - name: appname
      description: Name of the app to stage/run
    - name: organization
      description: The Organization under which the app is running
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: staging-$(uid)
        namespace: tekton-staging
        labels:
          app.kubernetes.io/name: $(tt.params.appname)
          app.kubernetes.io/part-of: $(tt.params.organization)
          app.kubernetes.io/managed-by: epinio
          app.kubernetes.io/component: staging
      spec:
        serviceAccountName: staging-triggers-admin
        pipelineRef:
          name: staging-pipeline
        workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        resources:
        - name: source-repo
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(tt.params.gitrevision)
            - name: url
              value: $(tt.params.gitrepositoryurl)
        - name: image
          resourceSpec:
            type: image
            params:
            - name: url
              value: registry.epinio-registry/apps/$(tt.params.appname)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: staging-pipelinebinding
  namespace: tekton-staging
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: tekton-staging
    - name: gitrepositoryurl
      value: "http://gitea-http.gitea:10080/$(body.repository.full_name)"
    - name: appname
      value: "$(body.repository.name)"
    - name: organization
      value: "$(body.repository.owner.login)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: staging-listener
  namespace: tekton-staging
spec:
  serviceAccountName: staging-triggers-admin
  triggers:
    - bindings:
      - ref: staging-pipelinebinding
      template:
        ref: staging-triggertemplate
      interceptors:
        - cel:
            # TODO: This is a reminder that this should match the HookSecret
            # on internal/cli/clients/client.go
            # If this filter is not set, anyone can trigger a staging job simply
            # by posting to the webhook.
            # More here: https://github.com/epinio/epinio/issues/130#issuecomment-813314112
            filter: "body.secret == '74tZTBHkhjMT5Klj6Ik6PqmM'"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: staging-pipeline
  namespace: tekton-staging
spec:
  workspaces:
  - name: source
  resources:
  - name: source-repo
    type: git
  - name: image
    type: image
  tasks:
  - name: clone
    taskRef:
      name: clone
    resources:
      inputs:
      - name: source-repo
        resource: source-repo
    workspaces:
    - name: source
      workspace: source
  - name: stage
    taskRef:
      name: buildpacks
    runAfter:
    - clone
    params:
    - name: BUILDER_IMAGE
      value: paketobuildpacks/builder:full
    - name: SOURCE_SUBPATH
      value: app
    resources:
      outputs:
      - name: image
        resource: image
    workspaces:
    - name: source
      workspace: source
  - name: run
    taskRef:
      name: run
    runAfter:
    - stage
    workspaces:
    - name: source
      workspace: source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone
  namespace: tekton-staging
spec:
  workspaces:
  - name: source
  resources:
    inputs:
    - name: source-repo
      type: git
      targetPath: source/app
  steps:
  - name: stage
    image: lachlanevenson/k8s-kubectl
    workingDir: "/workspace/source/app"
    command:
      - sh
    args:
      - -c
      - |
        pwd
        ls -la
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run
  namespace: tekton-staging
spec:
  workspaces:
  - name: source
  steps:
  - name: run
    image: lachlanevenson/k8s-kubectl
    workingDir: "/workspace/source/app"
    command:
      - sh
    args:
      - -c
      - |
        kubectl apply -f ./.kube/
