---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  rules:
    - host: "tekton.{{PUBLIC_IP}}.nip.io"
      http:
        paths:
          - backend:
              serviceName: tekton-dashboard
              servicePort: 9097
            path: /