name: Lint Commit Messages

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup gitlint
        run: sudo apt-get install gitlint
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint new commits
        run: gitlint --commits "origin/main..HEAD"
