name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go for Building
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.7'
      - name: Setup Ginkgo Test Framework
        run: go get -u github.com/onsi/ginkgo/ginkgo
      - name: Lint Carrier
        run: make lint
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools
      - name: Install Tools
        run: make tools-install
      - name: Install k3d
        run: wget -q -O k3d https://github.com/rancher/k3d/releases/download/v4.2.0/k3d-linux-amd64 && echo "745396701fb0ffaa832b02c5b734fd5b6bb042ac878b3ad16bb810ebbf02df0c k3d" | sha256sum --check --status && chmod +x k3d && mv k3d "`pwd`/output/bin"
      - name: Add Tools to PATH
        run: |
          echo "`pwd`/output/bin" >> $GITHUB_PATH
      - name: Run unit tests
        run: make test
      - name: Acceptance tests
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          make test-acceptance